FROM maven:3.3-jdk-8

ENV PLANTUML_VERSION=1.2018.13

RUN set -x \
 && wget https://github.com/plantuml/plantuml-server/archive/v${PLANTUML_VERSION}.tar.gz -O /plantuml.tar.gz \
 && mkdir /src \
 && cd /src \
 && tar xvfz /plantuml.tar.gz \
 && cd plantuml-server-${PLANTUML_VERSION} \
 && mvn clean package

WORKDIR /src/plantuml-server-${PLANTUML_VERSION}
CMD [ "cp", "./target/plantuml.war", "/dist/plantuml.war" ]